<?php
/**
 * This module provides integration to planorama webservice.
 * It is based upon the .NET implementation of the planorama
 * integration.
 *
 * @author Thomas Thune Hansen <tth@bellcom.dk>
 */
define('PLANORAMA_PAGES_COUNT', 2);

/**
 * Implements hook_menu()
 */
function planorama_menu() {
  $items = array();

  $items['admin/settings/planorama'] = array(
    'title' => 'Planorama',
    'description' => 'Configure planorama module',
    'access arguments' => array('configure planorama'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('planorama_settings'),
  );

  for ($page_index = 1; $page_index <= PLANORAMA_PAGES_COUNT; $page_index++) {
    if ($path = variable_get("planorama_path_$page_index", FALSE)) {
      $items[$path] = array(
        'title' => variable_get("planorama_title_$page_index", ''),
        'description' => 'Configure planorama module',
        'access arguments' => array('access planorama'),
        'page callback' => 'planorama_page',
        'page arguments' => array(strval($page_index)),//converting int to string to pass a literal value instead of reference
      );
    }
    if ($path = variable_get("planorama_search_path_$page_index", FALSE)) {
      $items[$path] = array(
        'title' => variable_get("planorama_search_title_$page_index", ''),
        'description' => 'Configure planorama module',
        'access arguments' => array('access planorama'),
        'page callback' => 'planorama_search_page',
        'page arguments' => array(strval($page_index)),//converting int to string to pass a literal value instead of reference
      );
    }
  }

  return $items;
}

/**
 * Implements hook_perm()
 */
function planorama_perm() {
  return array('configure planorama', 'access planorama');
}

/**
 * Settings form
 */
function planorama_settings() {
  $form['prefix'] = array(
    '#type' => 'item',
    '#description' => 'Please clear caches after updating settings.',
  );

  $form['planorama_api_key'] = array(
    '#default_value' => variable_get('planorama_api_key', ''),
    '#title'         => 'API key',
    '#type'          => 'textfield',
  );

  $form['planorama_url'] = array(
    '#default_value' => variable_get('planorama_url', ''),
    '#title'         => 'Planorama URL',
    '#type'          => 'textfield',
  );

  for ($page_index = 1; $page_index <= PLANORAMA_PAGES_COUNT; $page_index++) {
    $form["planorama_cat_$page_index-fs"] = array(
      '#type' => 'fieldset',
      '#title' => t('Category') . ' ' . $page_index,
      '#collapsible' => TRUE,
      '#collapsed' => FALSE,
    );
    $form["planorama_cat_$page_index-fs"]["planorama_cid_$page_index"] = array(
      '#default_value' => variable_get("planorama_cid_$page_index", ''),
      '#title'         => 'CategoryId',
      '#description'   => 'Default Category id',
      '#type'          => 'textfield',
    );
    $form["planorama_cat_$page_index-fs"]["planorama_path_$page_index"] = array(
      '#default_value' => variable_get("planorama_path_$page_index", ''),
      '#title'         => 'Local path',
      '#description'   => 'Enter the path where the planorama integration should be found',
      '#type'          => 'textfield',
    );
    $form["planorama_cat_$page_index-fs"]["planorama_title_$page_index"] = array(
      '#default_value' => variable_get("planorama_title_$page_index", ''),
      '#title'         => 'Page title',
      '#type'          => 'textfield',
    );
    $form["planorama_cat_$page_index-fs"]["planorama_search_path_$page_index"] = array(
      '#default_value' => variable_get("planorama_search_path_$page_index", ''),
      '#title'         => 'Local search path',
      '#description'   => 'Enter the path where the planorama search integration should be found',
      '#type'          => 'textfield',
    );
  }

  return system_settings_form($form);
}

/**
 * Implement hook_init()
 */
function planorama_init() {
  drupal_add_css(drupal_get_path('module', 'planorama') . '/css/PlanoramaWebcatalog.css');
}

/**
 * Planorama page
 */
function planorama_page($page_index) {
  $GLOBALS['conf']['cache'] = FALSE;
  // Get parameters
  $local_path = $_GET['q'];
  // Get planorama url from $path
  $params['APIKey'] = variable_get('planorama_api_key', '');
  $params['CatalogId'] = isset($_GET['cid']) ? $_GET['cid'] : variable_get("planorama_cid_$page_index", '');
  $params['ParentId'] = isset($_GET['pid']) ? $_GET['pid'] : '-1';
  $params['TemplateId'] = isset($_GET['tid']) ? $_GET['tid'] : '';
  $params['ActivityId'] = isset($_GET['signup']) ? $_GET['signup'] : '';
  $params['Data'] = isset($_POST['planorama_postdata']) ? $_POST['planorama_postdata'] : '';

  $plan_url = planorama_get_remote_url($path);
  $plan_path = planorama_get_remote_path($params);

  drupal_add_js(drupal_get_path('module', 'planorama') . '/js/jquery-1.7.min.js');
  drupal_add_js(drupal_get_path('module', 'planorama') . '/js/planorama.js');

  return planorama_get_page($plan_url . $plan_path, $params);
}

/**
 * Search page/
 */
function planorama_search_page($page_index) {
  $GLOBALS['conf']['cache'] = FALSE;
  $params['APIKey'] = variable_get('planorama_api_key', '');
  $params['SearchFor'] = isset($_GET['search']) ? $_GET['search'] : '';
  $params['ShowPath'] = variable_get("planorama_path_$page_index", '');

  $plan_url = planorama_get_remote_url($path);
  $plan_path = planorama_get_remote_path($params);

  $page = drupal_get_form('planorama_search', array('page_index' => $page_index));
  if (!empty($params['SearchFor'])) {
    $page .= planorama_get_page($plan_url . $plan_path, $params);
  }
  return $page;
}

function planorama_search($form_state, $vars = array()) {
  $form = array();

  $form['page_index'] = array(
    '#type' => 'hidden',
    '#value' => $vars['page_index'],
  );

  $form['search'] = array(
    '#type' => 'textfield',
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Search'),
  );

  return $form;
}

function planorama_search_submit($form, &$form_state) {
  drupal_goto(variable_get('planorama_search_path_' . $form_state['values']['page_index'], ''), array('search' => $form_state['values']['search']));
}

/**
 * Fetch the planorama remote url, specified for the drupal path
 */
function planorama_get_remote_url($path) {
  return variable_get('planorama_url', '');
}

/**
 * Depending on the parameters, we determine where to POST data
 */
function planorama_get_remote_path($params) {
  if (!empty($params['Data'])) {
    return 'public/public.asmx/Signup';
  } else if (!empty($params['ActivityId']) && !empty($params['TemplateId'])) {
    return 'public/public.asmx/GetSignupHtml';
  } else if (!empty($params['SearchFor'])) {
    return 'public/public.asmx/SearchWebcatalogs';
  } else if (!empty($params['TemplateId'])) {
    return 'public/public.asmx/GetCategoryTemplateHtml';
  } else {
    return 'public/public.asmx/GetCatalogHtml';
  }
}

/**
 * Fetch page content from planorama webservice
 */
function planorama_get_page($url, $params) {
  $ch = curl_init();
  $data = http_build_query($params, '', '&');
  $header = array(
    'Content-type: application/x-www-form-urlencoded',
    'Content-length: ' . strlen($data),
  );

  curl_setopt($ch, CURLOPT_URL, $url);
  curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
  curl_setopt($ch, CURLOPT_POST, 1);
  curl_setopt($ch, CURLOPT_TIMEOUT, 30000);
  curl_setopt($ch, CURLOPT_POSTFIELDS, $data);
  curl_setopt($ch, CURLOPT_FRESH_CONNECT, 1);
  curl_setopt($ch, CURLOPT_HTTPHEADER, $header);

  $output = curl_exec($ch);

  curl_close($ch);

  return '<form method="post" action="#">'
            . $output . '
            <div style="display: none">
              <input type="hidden" name="planorama_postdata" id="PostData">
              <input type="submit" name="planorama_submit" value="Submit" id="Submit">
            </div>
          </form>';
}
